### ISSUE TITLE
apps under /examples don't seem to work

### ISSUE THREAD

**Issue by threepointone** [automerge/automerge-repo#169] opened 2023-09-23 16:05 UTC
Hiya! I was trying to get the apps under `/examples` to run, but I suspect they've not been updated to the newer APIs? As an example, in /examples/automerge-repo-demo-counter, there's a type error here :
<img width="634" alt="image" src="https://github.com/automerge/automerge-repo/assets/18808/1f388b70-db3d-4f30-a453-8bb18f288da0">

Indeed, there's no url property on the object being returned, so the app never loads data, and never renders. 

(Additionally, `packages/automerge-repo-storage-nodefs/package.json` tries to install `rimraf@5`, but only works with `rimraf@4`)

Happy to help debug more if needed!

**Comment by pvh** [comment] 2023-09-30 20:55
Ah -- I think this is an error caused by my local `yarn` workspace config. If it doesn't see the URL property it's probably resolving the wrong (old) version of Automerge-Repo. I'll see if I can recreate this bug by checking out the repo from scratch but I suspect you can fix it by bumping the dependencies forward to "^1.0.0" in the package.json (if nobody's done this already.)

**Comment by threepointone** [comment] 2023-10-01 09:15
I went down the rabbit hold and made a PR https://github.com/automerge/automerge-repo/pull/173 that should fix it!

**Comment by pvh** [comment] 2023-10-01 17:58
Ah geez, I got up this morning and sat down to fix it without seeing your PR @threepointone.

**Comment by pvh** [comment] 2023-10-01 17:59
It looks like there are some good improvements to the overall structure in your PR, so I'll try and pull some of those bits in. Thanks for your efforts!

**Closed** 2023-10-01 18:17 UTC
